; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
upload_protocol = picotool
upload_port = COM10
lib_deps = stm32duino/STM32duino VL53L7CX@^1.0.3


[env:unoR3]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
lib_deps = 
    pololu/VL53L1X@^1.2.1

[env:esp_wroom_32]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
lib_deps = 
    https://components.espressif.com/components/grrtzm/v53l7cx-library
